# whitelist
branches:
only:
- galileo
- master
compiler:
- clang
before_script:
- "scons -c"
before_install:
- "git submodule init"
- "git submodule update"
- "sudo apt-get update -qq"
install:
- "mkdir fltklib"
- "cd fltklib && wget fltk.org/pub/fltk/snapshots/fltk-1.3.x-r10425.tar.bz2 && cd .."
- "cd fltklib && tar -xvf `ls` > /dev/null && cd `ls` && make > /dev/null && cp lib/libfltk.a ../../libfltk.a && cp -r FL ../../FL && cd ../../"
script: "scons -j8 fltklib=./libfltk.a --with-include=./"
