import os
import sys

Import("platformenv")

platform_files = [];

if sys.platform == 'darwin':
  platform_files += ["cocoa_pling.m"];
elif sys.platform.startswith('win'):
  platform_files += ["win32_getwindow.cpp"];
  platform_files += ["win32_pling.c"];
else:
  platform_files += ["generic_pling.cpp"];

platformlib = platformenv.StaticLibrary("kashyyyk_platform", platform_files)

Return("platformlib")

